---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: bankapps
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Test@123"
        - name: MYSQL_DATABASE
          value: "bankappdb"
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: bankapps
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
